{{ if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.deployment.name }}-issuer
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretRef }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.ingressClassName }}
{{ end }}
