repos:
  - repo: https://github.com/helm/chart-testing
    rev: v3.7.1
    hooks:
      - id: ct-lint
      - id: ct-install

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/yannh/kubeconform
    rev: v0.6.7
    hooks:
      - id: kubeconform
