{{ if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.metadata.name }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  {{ if .Values.storageClass.name }}
  storageClassName: {{ .Values.storageClass.name  }}
  {{ end }}
  volumeMode: {{ .Values.persistentVolume.mode }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
    type: DirectoryOrCreate
{{ end }}
