{{ if .Values.roleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.roleBinding.serviceAccount.targetAccount }}
  namespace: {{ .Values.roleBinding.serviceAccount.targetNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
