apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  labels:
    app: {{ .Values.deployment.name }}-svc
spec:
  type: {{ .Values.serviceTypee }}
  ports:
  {{ range .Values.portLists }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{ end }}
  selector:
    app: {{ .Values.deployment.name }}
