{{ if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-%s-pvc" .Values.deployment.name .Values.persistence.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ printf "%s-%s-pvc" .Values.deployment.name .Values.persistence.name }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{ end }}
