{{ if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.deployment.name }}-{{.Values.persistence.name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ .Values.deployment.name }}-{{ .Values.persistence.name }}-pvc
  storageClassName: {{ .Values.persistence.storageClass }}
{{ end }}
