{{- if .Values.secret.enabled }}
{{- range .Values.secret.secretLists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.deployment.name }}-{{ .name }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- if .Values.database.connectionString.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-db-config
data:
  connectiontring: {{ printf "%s://%s:%s@%s:5432/%s" .Values.database.connectionString.type .Values.database.userName .Values.database.password .Values.database.host .Values.database.name }}
{{- end }}
