{{ if .Values.secret.enabled }}
{{ range .Values.secret.secretLists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.deployment.name }}-{{ .name }}
data:
  {{ range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{ end }}
---
{{ end }}
{{ end }}
{{ if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-db-connection
data:
  {{ if .Values.database.connectionString.enabled }}
  connectionString: {{ (printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=%s;SearchPath=%s" .Values.database.host .Values.database.port .Values.database.name .Values.database.username .Values.database.password .Values.database.schema) | b64enc }}
  {{ end }}
  {{ if .Values.database.migrationString.enabled }}
  migrationDbString: {{ (printf "%s://%s:%s@%s:%s/%s?schema=%s" .Values.database.databaseType .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name .Values.database.schema) | b64enc }}
  {{ end }}
{{ end }}
---
{{ if .Values.privateRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.privateRegistry.registry .Values.privateRegistry.username .Values.privateRegistry.password) | b64enc }}
{{ end }}
---
{{ if .Values.redisCredential.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-redis-secrets
data:
  REDIS_HOST: {{ .Values.redisCredential.host | default "redis" | b64enc }}
  REDIS_PORT: {{ .Values.redisCredential.port | default "6379" | b64enc }}
  REDIS_PASSWORD: {{ .Values.redisCredential.password | default "" | b64enc }}
  REDIS_USERNAME: {{ .Values.redisCredential.username | default "" | b64enc }}
---
{{ end}}
---
{{ if .Values.database.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-db-credentials
data:
  DATABASE_HOST: {{ .Values.database.host | b64enc }}
  DATABASE_PORT: {{ .Values.database.port | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | b64enc }}
  DATABASE_USERNAME: {{ .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
{{ end }}
