{{- if and .Values.gateway.traefik.enabled .Values.gateway.cors.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-cors" .Values.deployment.name }}
spec:
  headers:
    accessControlAllowMethods:
    {{- .Values.gateway.cors.methodLists | toYaml | nindent 6 }}
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
    {{- .Values.gateway.cors.originLists | toYaml | nindent 6 }}
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end }}
{{- if and .Values.gateway.traefik.enabled .Values.gateway.customHeaders }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-custom-headers" .Values.deployment.name }}
spec:
  headers:
    {{- toYaml .Values.gateway.customHeaders | nindent 4 }}
{{- end }}
{{- if and .Values.gateway.traefik.enabled .Values.gateway.s3Behavior.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: range-request-headers
spec:
  headers:
    customRequestHeaders:
      Range: "{http_range}"
      If-Range: "{http_if_range}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-response-headers
spec:
  headers:
    customResponseHeaders:
      Accept-Ranges: "bytes"
      Cache-Control: "no-store"
      X-Frame-Options: "DENY"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "strict-origin-when-cross-origin"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-bucket-rewrite" .Values.deployment.name }}
spec:
  replacePathRegex:
    regex: ^/(.*)
    replacement: {{ printf "/%s/$1" .Values.gateway.s3Behavior.bucketName  }}
{{- if and .Values.gateway.traefik.enabled .Values.gateway.s3Behavior.spa.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-spa-root" .Values.deployment.name }}
spec:
  replacePathRegex:
    regex: ^/$
    replacement: {{ printf "/%s/index.html" .Values.gateway.s3Behavior.bucketName  }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-spa-errors" .Values.deployment.name }}
spec:
  errors:
    status:
      - "400"
      - "403"
      - "404"
    service:
      name: {{ .Values.gateway.s3Behavior.s3Service }}
      port: {{ .Values.gateway.s3Behavior.s3Port }}
    query: {{ printf "/%s/index.html" .Values.gateway.s3Behavior.bucketName  }}
{{- end }}
{{- end }}
