{{- if .Values.externalSecret.enabled }}
{{- if or .Values.externalSecret.onepassword.allKeyOneSecret.enabled .Values.externalSecret.onepassword.data .Values.externalSecret.onepassword.allKeyMultiSecrets.enabled }}
{{- if and (or .Values.externalSecret.onepassword.allKeyOneSecret.enabled .Values.externalSecret.onepassword.allKeyMultiSecrets.enabled) .Values.externalSecret.onepassword.data }}
{{ fail "Only one of allKeyOneSecret / allKeyMultiSecrets or onepassword.data can be enabled at the same time!" }}
{{- end }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-onepassword-secret-fetcher" .Values.deployment.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "48h" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-store" .Values.deployment.name }}
  target:
    creationPolicy: Owner
  {{- if .Values.externalSecret.onepassword.allKeyOneSecret.enabled }}
    template:
      type: Opaque
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |-
          {{`{{- $envMap := fromJson .envJson -}}`}}
          {{`{{- range $key, $val := $envMap }}`}}
          {{`{{ $key }}: {{ $val }}`}}
          {{`{{- end -}}`}}
  data:
    - secretKey: envJson
      remoteRef:
        key: {{ .Values.externalSecret.onepassword.item }}/{{ .Values.externalSecret.onepassword.allKeyOneSecret.field }}
  {{- else if .Values.externalSecret.onepassword.allKeyMultiSecrets.enabled }}
    template:
      type: Opaque
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |-
          {{`{{- $envMap := fromJson .envJson -}}`}}
          {{`{{- range $key, $val := $envMap }}`}}
          {{`{{ $key }}: {{ $val }}`}}
          {{`{{- end -}}`}}
    data:
    {{- range .Values.externalSecret.onepassword.allKeyMultiSecrets.fields }}
      - secretKey: envJson-{{ . | lower }}
        remoteRef:
          key: {{ $.Values.externalSecret.onepassword.item }}/{{ . }}
    {{- end }}
  {{ else }}
  data:
    {{- /*
    # Splits the multiline string into lines.
    # Removes whitespace
    # Ensures blank lines are skipped
    */}}
    {{- if .Values.externalSecret.onepassword.data }}
    {{- range $name := splitList "\n" .Values.externalSecret.onepassword.data }}
    {{ $trimmed := trim $name }}
    {{ if $trimmed }}
      - secretKey: {{ $trimmed }}
        remoteRef:
          key: {{ printf "%s/%s" $.Values.externalSecret.onepassword.item  ($trimmed) }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- /*
    # Get Specific values from 1Password
    */}}
    {{- if .Values.externalSecret.onepassword.secretLists }}
    {{- range .Values.externalSecret.onepassword.secretLists }}
      - secretKey: {{ .name }}
        remoteRef:
          key: {{ printf "%s/%s" $.Values.externalSecret.onepassword.item  (.name) }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- /*
  # At the moment External Secret does not support creating multiple secrets from one ExternalSecret object
  # Ref: https://stackoverflow.com/a/77091265
*/}}
---
{{- if .Values.externalSecret.onepassword.multiSecrets.enabled }}
{{- range .Values.externalSecret.onepassword.multiSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s-secret-fetcher" $.Values.deployment.name .name }}
spec:
  refreshInterval: 48h
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-store" $.Values.deployment.name }}
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |-
          {{`{{- $envMap := fromJson .envJson -}}`}}
          {{`{{- range $key, $val := $envMap }}`}}
          {{`{{ $key }}: {{ $val }}`}}
          {{`{{- end -}}`}}
  data:
    - secretKey: envJson
      remoteRef:
        key: {{ printf "%s/%s" .name .field }}
{{- end }}
{{- end }}
{{ if .Values.externalSecret.privateRegistry.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-docker-registry" .Values.deployment.name }}
spec:
  refreshInterval: 48h
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-store" .Values.deployment.name }}
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ "{{" }}.registry{{ "}}" }}":{"username": "{{ "{{" }}.username{{ "}}" }}","password": "{{ "{{" }}.password{{ "}}" }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: {{ $.Values.externalSecret.privateRegistry.onepasswordItem | default "Harbor Robot" }}/username
    - secretKey: password
      remoteRef:
        key: {{ $.Values.externalSecret.privateRegistry.onepasswordItem | default "Harbor Robot" }}/password
    - secretKey: registry
      remoteRef:
        key: {{ $.Values.externalSecret.privateRegistry.onepasswordItem | default "Harbor Robot" }}/registry
{{- end }}
{{- if or .Values.externalSecret.aws.parameterStore.enabled .Values.externalSecret.aws.sercretManager.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-aws-secret-fetcher" .Values.deployment.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "48h" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-store" .Values.deployment.name }}
  target:
    creationPolicy: Owner
    {{- if .Values.externalSecret.aws.dataFrom.enabled }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.aws.dataFrom.keyPath }}
    {{- end }}
    {{- if .Values.externalSecret.aws.allKeyOneSecret.enabled }}
    template:
      type: Opaque
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |-
          {{`{{- $envMap := fromJson .envJson -}}`}}
          {{`{{- range $key, $val := $envMap }}`}}
          {{`{{ $key }}: {{ $val }}`}}
          {{`{{- end -}}`}}
  data:
    - secretKey: envJson
      remoteRef:
        key: {{ .Values.externalSecret.aws.allKeyOneSecret.keyPath }}
        version: {{ .Values.externalSecret.aws.allKeyOneSecret.version | default "AWSCURRENT" }}
    {{- end }}
    {{- if .Values.externalSecret.aws.secretList }}
  data:
  {{- range .Values.externalSecret.aws.secretList }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .keyPath }}
        version: {{ .version | default "AWSCURRENT" }}
  {{- end }}
  {{- end }}
{{- end }}
