{{ if .Values.secret.enabled }}
{{ range .Values.secret.secretLists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Values.deployment.name .name }}
data:
  {{ range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{ end }}
---
{{ end }}
{{ end }}
