{{ if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ printf "%s-secret-store" .Values.deployment.name }}
spec:
  provider:
  {{- if .Values.externalSecret.onepassword.connectServer }}
    onepassword:
      connectHost: {{ .Values.externalSecret.onepassword.connectHost }}
      vaults:
        {{ .Values.externalSecret.onepassword.vaultName }}: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: {{ .Values.externalSecret.onepassword.tokenName | default "op-credentials" }}
            key: {{ .Values.externalSecret.onepassword.tokenKey | default "token" }}
            namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.externalSecret.onepassword.sdk }}
    onepasswordSDK:
      vault: {{ .Values.externalSecret.onepassword.vaultName }}
      auth:
        serviceAccountSecretRef:
          name: {{ .Values.externalSecret.onepassword.tokenName | default "op-credentials" }}
          key: {{ .Values.externalSecret.onepassword.tokenKey | default "token" }}
      integrationInfo: # this is optional and defaulted
        name: integration-info
        version: v1
  {{- end }}
  {{- if and .Values.externalSecret.onepassword.connectServer .Values.externalSecret.onepassword.sdk }}
  {{- fail "Only one of externalSecret.onepassword.connectServer or externalSecret.onepassword.sdk can be enabled at the same time!" }}
  {{- end }}
  {{- if and .Values.externalSecret.aws.sercretManager.enabled .Values.externalSecret.aws.parameterStore.enabled }}
  {{- fail ".Values.externalSecret.aws.sercretManager.enabled or .Values.externalSecret.aws.parameterStore.enabled can be enabled at the same time!" }}
  {{- end }}
  {{- if or .Values.externalSecret.aws.sercretManager.enabled .Values.externalSecret.aws.parameterStore.enabled }}
    aws:
      {{- if .Values.externalSecret.aws.sercretManager.enabled }}
      service: SecretsManager
      {{- else if .Values.externalSecret.aws.parameterStore.enabled }}
      service: ParameterStore
      {{- end }}
      region: {{ .Values.externalSecret.aws.region | default "us-east-1" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecret.aws.secretName | default "awssm-secret" }}
            key: {{ .Values.externalSecret.aws.accessKeyName | default "access-key" }}
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecret.aws.secretName | default "awssm-secret" }}
            key: {{ .Values.externalSecret.aws.secretAccessKeyName | default "secret-access-key" }}
  {{- end }}
{{- /*
################## Attention ###############################
# Please the the kube command like this to create the
# 1password token secret after the argo application is
# created:
# kubectl create secret generic op-credentials \
# --from-literal=token="<token-here>" -n <namespace-here>
############################################################
*/}}
{{- end }}
