{{ if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-db-connection
data:
  {{ if .Values.database.connectionString.enabled }}
  connectionString: {{ (printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=%s;SearchPath=%s" .Values.database.host .Values.database.port .Values.database.name .Values.database.username .Values.database.password .Values.database.schema) | b64enc }}
  {{ end }}
  {{ if .Values.database.migrationString.enabled }}
  migrationDbString: {{ (printf "%s://%s:%s@%s:%s/%s?schema=%s" .Values.database.databaseType .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name .Values.database.schema) | b64enc }}
  {{ end }}
{{ end }}
---
{{ if .Values.database.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-db-credentials
data:
  DATABASE_HOST: {{ .Values.database.host | b64enc }}
  DATABASE_PORT: {{ .Values.database.port | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | b64enc }}
  DATABASE_USERNAME: {{ .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
{{ end }}
