{{ if .Values.privateRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.privateRegistry.registry .Values.privateRegistry.username .Values.privateRegistry.password) | b64enc }}
{{ end }}
